my:
  greeting: Hello World from Config Server
  list:
    values: One, Two, Three
    
spring.application.name:movie-catalog-service

server.port:8081

management.endpoints.web.exposure.include:hystrix.stream
